# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoDataDialog
                                 A QGIS plugin
 This plugin gathers cz/sk data sources.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-04
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Test
        email                : test
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
import importlib, inspect
#from .lib.eea_geomorphology.eea_geomorphology import eea_geomorphology
from .plugins.plugin import Plugin

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Geo_Data_dialog_base.ui'))


class GeoDataDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GeoDataDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.plugins = []
        self.load_plugins()
        self.print_plugins_metadata()

    def load_plugins(self):
        # Used from https://stackoverflow.com/questions/3178285/list-classes-in-directory-python
        current_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)))
        current_module_name = os.path.splitext(os.path.basename(current_dir))[0]
        plugins_dir = os.path.join(current_dir, 'plugins')
        paths = [ name for name in os.listdir(plugins_dir) if os.path.isdir(os.path.join(plugins_dir, name)) ]
        for path in paths:
            if not path.startswith("__"):
                print(path)
                module = importlib.import_module(".plugins." + path + ".source", package=current_module_name)
                for member in dir(module):
                    print(member)
                    if member != 'Plugin':
                        handler_class = getattr(module, member)
                        if handler_class and inspect.isclass(handler_class) and issubclass(handler_class, Plugin):
                            self.plugins.append(handler_class())

    def print_plugins_metadata(self):
        for plugin in self.plugins:
            print("META: " + plugin.get_metadata().name + " " + plugin.get_metadata().description)
